# Generated by Django 5.2.2 on 2025-06-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoporteInformatica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='realizada',
            field=models.BooleanField(default=False),
        ),
    ]
