# Generated by Django 5.2.2 on 2025-06-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoporteInformatica', '0002_ticket_realizada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='realizada',
            new_name='estado_peticion',
        ),
    ]
