# Generated by Django 5.2.2 on 2025-06-23 20:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoporteInformatica', '0003_rename_realizada_ticket_estado_peticion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='tarea_completada',
            field=models.DateTimeField(null=True),
        ),
    ]
