# Generated by Django 5.2.2 on 2025-06-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoporteInformatica', '0004_ticket_fecha_creacion_ticket_tarea_completada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tarea_completada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
