# Generated by Django 5.2.2 on 2025-06-26 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoporteInformatica', '0005_alter_ticket_tarea_completada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='estado_peticion',
        ),
    ]
