# Generated by Django 5.2.2 on 2025-07-07 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoporteInformatica', '0006_remove_ticket_estado_peticion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='descripcion',
            new_name='detalle',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='titulo',
            new_name='nombre',
        ),
    ]
