# Generated by Django 5.2.2 on 2025-07-07 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoporteInformatica', '0007_rename_descripcion_ticket_detalle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relacion_problema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='oficina',
            field=models.CharField(default='Sin oficina', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='relacion_problema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SoporteInformatica.relacion_problema'),
        ),
    ]
