# Generated by Django 5.2.2 on 2025-07-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoporteInformatica', '0008_relacion_problema_ticket_correo_ticket_oficina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='oficina',
            field=models.CharField(max_length=100),
        ),
    ]
