# Generated by Django 5.2.2 on 2025-07-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoporteInformatica', '0009_alter_ticket_oficina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='nombre',
        ),
    ]
